name: Release
on:
  push:
    tags:
      - "v*"

env:
  PLUGIN_NAME: obsidian-file-cleaner
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r "${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip" ${{ env.PLUGIN_NAME }}

  create-github-release:
    name: Create release
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref}} --generate-notes \
            main.js manifest.json styles.json \
            "${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip"
